
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

void
gedit_file_browser_enum_and_flag_register_type (GTypeModule * module)
{
	/* Enumerations from "gedit-file-browser-error.h" */
	register_gedit_file_browser_error (module);
	/* Enumerations from "gedit-file-browser-store.h" */
	register_gedit_file_browser_store_column (module);
	register_gedit_file_browser_store_flag (module);
	register_gedit_file_browser_store_result (module);
	register_gedit_file_browser_store_filter_mode (module);
	/* Enumerations from "gedit-file-browser-view.h" */
	register_gedit_file_browser_view_click_policy (module);
}

/* Generated data ends here */

