
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#ifndef GEDIT_ENUM_TYPES_H
#define GEDIT_ENUM_TYPES_H

#include <glib-object.h>

G_BEGIN_DECLS
/* Enumerations from "/home/teste/Documents/gedit/_build/../gedit/gedit-app.h" */
#define GEDIT_TYPE_LOCKDOWN_MASK	(gedit_lockdown_mask_get_type())
GType gedit_lockdown_mask_get_type	(void) G_GNUC_CONST;
/* Enumerations from "/home/teste/Documents/gedit/_build/../gedit/gedit-debug.h" */
#define GEDIT_TYPE_DEBUG_SECTION	(gedit_debug_section_get_type())
GType gedit_debug_section_get_type	(void) G_GNUC_CONST;
/* Enumerations from "/home/teste/Documents/gedit/_build/../gedit/gedit-notebook.h" */
#define GEDIT_TYPE_NOTEBOOK_SHOW_TABS_MODE_TYPE	(gedit_notebook_show_tabs_mode_type_get_type())
GType gedit_notebook_show_tabs_mode_type_get_type	(void) G_GNUC_CONST;
/* Enumerations from "/home/teste/Documents/gedit/_build/../gedit/gedit-tab.h" */
#define GEDIT_TYPE_TAB_STATE	(gedit_tab_state_get_type())
GType gedit_tab_state_get_type	(void) G_GNUC_CONST;
/* Enumerations from "/home/teste/Documents/gedit/_build/../gedit/gedit-window.h" */
#define GEDIT_TYPE_WINDOW_STATE	(gedit_window_state_get_type())
GType gedit_window_state_get_type	(void) G_GNUC_CONST;
G_END_DECLS

#endif /* GEDIT_ENUM_TYPES_H */

/* Generated data ends here */

