/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define DATADIR "/usr/local/share"

#define GEDIT_MAJOR_VERSION 3

#define GEDIT_MICRO_VERSION 0

#define GEDIT_MINOR_VERSION 32

#define GETTEXT_PACKAGE "gedit"

#define LIBDIR "/usr/local/lib/x86_64-linux-gnu"

#define LOCALEDIR "/usr/local/share/local"

#define PACKAGE_NAME "gedit"

#define PACKAGE_STRING "gedit-3.14"

#define PACKAGE_VERSION "3.32.0"

#define VERSION "3.32.0"

